environment:
  global:
    TOXENV: "py"

  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"

init:
  - SET PATH=%PYTHON%;%PATH%
  - python -c "import sys;sys.stdout.write(sys.version)"

install:
  - python -m pip install -U pip setuptools wheel tox

build: false

test_script:
  - python -m tox

branches:
  only:
    - master
    - /^.*-maintenance$/
