language: python

python:
  - 2.6
  - 2.7
  - pypy
  - 3.3

install: pip install --editable .

script: make test

branches:
  except:
    - website

notifications:
  # Disable travis notifications until they figured out how to hide
  # their own builder failure from us.  Travis currently fails way
  # too many times by itself.
  email: false
