sudo: false
language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=py-release,codecov
    - python: 3.5
      env: TOXENV=py-release,codecov
    - python: 3.4
      env: TOXENV=py-release,codecov
    - python: 3.3
      env: TOXENV=py-release,codecov
    - python: 2.7
      env: TOXENV=py-release,codecov
    - python: 2.6
      env: TOXENV=py-release,codecov
    - python: pypy
      env: TOXENV=py-release,codecov
    - python: nightly
      env: TOXENV=py-release
    - python: 3.6
      env: TOXENV=docs-html
    - python: 3.6
      env: TOXENV=py-release-simplejson,codecov

install:
  - pip install tox

script:
  - tox

cache:
  - pip

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#pocoo"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
